export const ADVENTURE_BUFFS = [
    { id: 'buff_droid', name: 'Droiden-Netzwerk', desc: 'Am Ende jeder Runde erhältst du +5 Punkte pro Droide auf deiner Hand.' },
    { id: 'buff_klon', name: 'Klon-Disziplin', desc: 'Spielst du zwei Klone hintereinander, erhält der zweite +20 Punkte.' },
    { id: 'buff_rebell', name: 'Rebellen-Hoffnung', desc: 'Liegst du am Rundenanfang zurück, erhält deine Karte +20% Basis-Punkte.' },
    { id: 'buff_ersteordnung', name: 'Diktatur', desc: 'Gewinnst du eine Runde, verliert der Gegner nächste Runde 15 Punkte.' },
    { id: 'buff_imperium', name: 'Orbitalschlag', desc: 'Zu Beginn jedes Matches wird dem Gegner 1 zufällige Karte zerstört.' },
    { id: 'buff_nachtschwester', name: 'Nekromantie', desc: 'Wenn du keine Karten mehr hast, erhältst du 1 zerstörte Karte zurück.' },
    { id: 'buff_schurke', name: 'Taschendieb', desc: 'Du klaust zu Beginn des Matches 30 Punkte vom gegnerischen Start-Score.' },
    { id: 'buff_bounty', name: 'Kopfgeld', desc: 'Besiegst du eine Karte der Seltenheit Epic oder Legendary, erhältst du +30 Punkte.' },
    { id: 'buff_mandalorian', name: 'Beskar-Rüstung', desc: 'Der erste negative Boss-Effekt in einem Match wird blockiert.' },
    { id: 'buff_senat', name: 'Bürokratie', desc: 'Die erste gespielte Karte des Gegners in einem Match zählt nicht (0 Punkte).' },
    { id: 'buff_fahrzeug', name: 'Überrollen', desc: 'Deine Fahrzeuge erhalten permanent +30% Stats.' },
    { id: 'buff_grey', name: 'Balance der Macht', desc: 'Liegen beide Scores weniger als 20 Punkte auseinander, erhältst du +40 Punkte.' },
    { id: 'buff_sith', name: 'Sith-Zorn', desc: 'Verlierst du eine Runde mit mehr als 50 Punkten Rückstand, erhält deine nächste Karte +50% Stats.' },
    { id: 'buff_jedi', name: 'Jedi-Meditation', desc: 'Du startest jedes Match mit +50 Punkten Vorsprung.' },
    { id: 'buff_widerstand', name: 'Verzweiflungstat', desc: 'Deine allerletzte Karte auf der Hand erhält +100% Stats.' },
    { id: 'buff_separatist', name: 'Übermacht', desc: 'Hast du mehr Karten auf der Hand als der Gegner, erhalten alle deine Karten +10 Punkte.' },
    { id: 'buff_monster', name: 'Raserei', desc: 'Jede deiner Karten hat eine 50% Chance auf +30 Punkte, aber 50% Chance auf -15 Punkte.' },
    { id: 'buff_schmuggel', name: 'Schmuggelware', desc: 'Du startest jedes Match mit einer extra Karte auf der Hand.' },
    { id: 'buff_212th', name: 'High Ground', desc: 'Jeder eingesetzte Klon des 212th Bataillons kopiert den Multiplikator des Gegners, falls dieser höher ist.' },
    { id: 'buff_501st', name: 'Vaders Faust', desc: 'Jeder eingesetzte Klon der 501st Legion verringert den Score des Gegners um 10 Punkte.' },
    { id: 'buff_badbatch', name: 'Klon-Einheit 99', desc: 'Alle Bad Batch Mitglieder erhalten +50 Punkte, aber du wählst sie blind.' },
    { id: 'buff_hutte', name: 'Erpressung', desc: 'Die stärkste Karte des Gegners startet mit -30 Punkten in das Match.' }
];
