const fs = require('fs');

let file = fs.readFileSync('d:/Programmieren/Ranker/index.html', 'utf8');

const exclusiveHtml = `                                <div class="has-tooltip" data-tooltip="Silence: Der Mandalorianer nutzt Beskar, um gegnerische Buff-Fähigkeiten (Score-Modifikatoren) für diese Runde komplett zu annullieren.&#10;&#10;  Ende: Die Silence-Wirkung hält genau eine Runde an.&#10;  Limit: Exklusiv (Maximal 3 erlaubt)" style="cursor:help; padding:3px 6px; background:#ff9f4333; color:#ff9f43; border-radius:4px; border:1px solid #ff9f43;">Mandalorianer</div>
                                <div class="has-tooltip" data-tooltip="Ausgleich: Die Grauen Machtnutzer streben nach Balance. In der Endabrechnung des Matches (Sieg/Niederlage) gewinnt ausnahmsweise derjenige, der WENIGER Runden gewonnen hat.&#10;&#10;  Ende: Die Regelumkehr gilt permanent für den finalen Ausgang des gesamten Matches.&#10;  Limit: Exklusiv (Maximal 1 erlaubt)" style="cursor:help; padding:3px 6px; background:#ccc3; color:#ccc; border-radius:4px; border:1px solid #ccc;">Grau</div>
                                <div class="has-tooltip" data-tooltip="Veto: Verhindert eine direkte Niederlage. Falls dein Gegner gewinnen würde, wird das Ergebnis auf ein Unentschieden (0:0) eingefroren.&#10;&#10;  Ende: Gilt nur für diese eine Runde.&#10;  Limit: Exklusiv (Maximal 3 erlaubt)" style="cursor:help; padding:3px 6px; background:#4da6ff33; color:#4da6ff; border-radius:4px; border:1px solid #4da6ff;">Senat</div>
                                <div class="has-tooltip" data-tooltip="Überrollen: Gewinnt das Fahrzeug die Runde, greift es sofort in einer Extra-Runde nochmals an und behält seinen Score.&#10;&#10;  Ende: Endet sofort und das Fahrzeug wird zerstört, falls es eine Runde verliert.&#10;  Limit: Exklusiv (Maximal 3 erlaubt)" style="cursor:help; padding:3px 6px; background:#aaa3; color:#aaa; border-radius:4px; border:1px solid #aaa;">Fahrzeuge</div>
                                <div class="has-tooltip" data-tooltip="Ausdünnung: Jede zweite (2.) gespielte Sith-Karte vernichtet sofort und dauerhaft eine zufällige Karte direkt von der feindlichen Hand.&#10;&#10;  Ende: Der Zähler ist während des gesamten Matches permanent aktiv.&#10;  Limit: Exklusiv (Maximal 4 erlaubt)" style="cursor:help; padding:3px 6px; background:#cc444433; color:#cc4444; border-radius:4px; border:1px solid #cc4444;">Sith</div>
                                <div class="has-tooltip" data-tooltip="Gedankentrick: Spielst du einen Jedi, zwingt dieser den Bot dazu, in seiner NÄCHSTEN Runde garantiert seine schwächste Karte auszuspielen.&#10;&#10;  Ende: Der Effekt verbraucht sich automatisch beim Ausspielen der gegnerischen Karte.&#10;  Limit: Exklusiv (Maximal 3 erlaubt)" style="cursor:help; padding:3px 6px; background:#5dade233; color:#5dade2; border-radius:4px; border:1px solid #5dade2;">Jedi</div>
                                <div class="has-tooltip" data-tooltip="Flucht: Schmuggler lassen sich ungern schnappen. Verliert der Schmuggler die Runde, wird er nicht zerstört, sondern mischt sich unauffällig zurück in dein Nachzieh-Deck.&#10;&#10;  Limit: Exklusiv (Maximal 3 erlaubt)" style="cursor:help; padding:3px 6px; background:#a0522d33; color:#a0522d; border-radius:4px; border:1px solid #a0522d;">Schmuggel</div>
                                <div class="has-tooltip" data-tooltip="Erpressung: Spielst du einen Hutten, zwingt dieser den Bot dazu, in seiner NÄCHSTEN Runde garantiert seine STÄRKSTE verbleibende Karte auszuspielen (Gegenteil vom Jedi).&#10;&#10;  Limit: Exklusiv (Maximal 2 erlaubt)" style="cursor:help; padding:3px 6px; background:#2e8b5733; color:#2e8b57; border-radius:4px; border:1px solid #2e8b57;">Hutte</div>
                                <div class="has-tooltip" data-tooltip="Vaders Faust: Gewinnt die 501st Legion ihre Runde, kennt sie keine Gnade und vernichtet sofort die nächste Karte auf dem gegnerischen Nachzieh-Deck. (Erfordert Anakin Skywalker oder Darth Vader im Deck).&#10;&#10;  Limit: Exklusiv (Maximal 3 erlaubt)" style="cursor:help; padding:3px 6px; background:#00008b33; color:#6a6aff; border-radius:4px; border:1px solid #00008b;">501st</div>
                                <div class="has-tooltip" data-tooltip="High Ground: Die 212th agiert taktisch. Ist der Rarity-Multiplikator des Gegners höher als der eigene, wird dieser einfach kopiert und übernommen.&#10;&#10;  Limit: Exklusiv (Maximal 3 erlaubt)" style="cursor:help; padding:3px 6px; background:#d2691e33; color:#d2691e; border-radius:4px; border:1px solid #d2691e;">212th</div>
                                <div class="has-tooltip" data-tooltip="Kloneinheit 99: Massiver +4.0 Buff. Da sie aber Befehle verweigern, darfst du in deiner NÄCHSTEN Runde deine Karte nicht selbst wählen (Zufallszug).&#10;&#10;  Limit: Exklusiv (Maximal 2 erlaubt)" style="cursor:help; padding:3px 6px; background:#69696933; color:#696969; border-radius:4px; border:1px solid #696969;">Bad Batch</div>`;

const formationHtml = `                                <div class="has-tooltip" data-tooltip="Falsches Spiel: Vor der Gewinn-Ermittlung stiehlt der Schurke heimlich den aktuellen Score des Gegners und tauscht ihn gegen seinen eigenen.&#10;&#10;  Ende: Die geklauten Werte gelten ausschließlich in dieser Runde.&#10;  Limit: Formation (Mindestens 3 benötigt)" style="cursor:help; padding:3px 6px; background:#e67e2233; color:#e67e22; border-radius:4px; border:1px solid #e67e22;">Schurke</div>
                                <div class="has-tooltip" data-tooltip="Unterdrückung: Gewinnt das Imperium, baut es starken Druck auf. Die gegnerische Karte in der NÄCHSTEN Runde verliert pauschal 25% Basis-Score.&#10;&#10;  Ende: Verliert das Imperium, triggert der Effekt nicht. Der 25% Abzug verfällt nach 1 Runde.&#10;  Limit: Formation (Mindestens 4 benötigt)" style="cursor:help; padding:3px 6px; background:#8883; color:#888; border-radius:4px; border:1px solid #888;">Imperium</div>
                                <div class="has-tooltip" data-tooltip="Hoffnung: Rebellen kämpfen aus Verzweiflung stärker. Liegst du im aktuellen Gesamt-Match hinten (weniger Siege), verdoppelt der Rebell seinen Score.&#10;&#10;  Ende: Sobald du Gleichstand erreichst oder führst, entfällt die Verdopplung.&#10;  Limit: Formation (Mindestens 4 benötigt)" style="cursor:help; padding:3px 6px; background:#e74c3c33; color:#e74c3c; border-radius:4px; border:1px solid #e74c3c;">Rebell</div>
                                <div class="has-tooltip" data-tooltip="Klon-Kette: Stirbt ein Klon, wird sein Score global gespeichert. Der nächste gespielte Klon erhält diesen Score als permanenten Boost oben drauf.&#10;&#10;  Ende: Die Kette reißt sofort ab (Bonus = 0), wenn zwischen zwei Klonen eine andere Fraktion gespielt wird.&#10;  Limit: Formation (Mindestens 4 benötigt)" style="cursor:help; padding:3px 6px; background:#f1c40f33; color:#f1c40f; border-radius:4px; border:1px solid #f1c40f;">Klon</div>
                                <div class="has-tooltip" data-tooltip="Nekromantie: Gewinnt die Nachtschwester, holt sie mit dunkler Magie die vom Gegner ZULETZT besiegte Karte aus dem feindlichen Friedhof in deine Hand.&#10;&#10;  Ende: Funktioniert nur bei einem aktiven Rundensieg.&#10;  Limit: Formation (Mindestens 3 benötigt)" style="cursor:help; padding:3px 6px; background:#9b59b633; color:#9b59b6; border-radius:4px; border:1px solid #9b59b6;">Nachtschwester</div>
                                <div class="has-tooltip" data-tooltip="Verschmelzung: Spielst du diesen Droiden, verdoppelt sich durch Schwarm-Intelligenz automatisch der Score deines NÄCHSTEN Droiden.&#10;&#10;  Ende: Der Verdopplungs-Bonus wird direkt beim Einsatz des nächsten Droiden verbraucht.&#10;  Limit: Formation (Mindestens 5 benötigt)" style="cursor:help; padding:3px 6px; background:#95a5a633; color:#95a5a6; border-radius:4px; border:1px solid #95a5a6;">Droid</div>
                                <div class="has-tooltip" data-tooltip="Kopfgeld: Zu Beginn des Matches wird die häufigste feindliche Fraktion als Ziel markiert. Besiegst du dieses Ziel im Duell, erhältst du 2 Match-Punkte (statt 1).&#10;&#10;  Ende: Das Hauptziel bleibt das ganze Match über dauerhaft markiert.&#10;  Limit: Formation (Mindestens 3 benötigt)" style="cursor:help; padding:3px 6px; background:#34495e33; color:#34495e; border-radius:4px; border:1px solid #34495e;">Kopfgeldjäger</div>
                                <div class="has-tooltip" data-tooltip="Zwangsrekrutierung: Gewinnt die Erste Ordnung, wird die gerade besiegte feindliche Karte nicht zerstört, sondern sofort in deine eigene Hand rekrutiert.&#10;&#10;  Ende: Der Effekt ist nur während der exakten Runde des Sieges aktiv.&#10;  Limit: Formation (Mindestens 4 benötigt)" style="cursor:help; padding:3px 6px; background:#e74c3c33; color:#e74c3c; border-radius:4px; border:1px solid #e74c3c;">Erste Ordnung</div>
                                <div class="has-tooltip" data-tooltip="Opfermut: Verliert ein Widerstandskämpfer, inspiriert sein Opfer das Team. Deine NÄCHSTE ausgespielte Karte erhält einen massiven Bonus von +4.0 Punkten.&#10;&#10;  Ende: Der Bonus verbraucht sich direkt in der Folgerunde.&#10;  Limit: Formation (Mindestens 4 benötigt)" style="cursor:help; padding:3px 6px; background:#f39c1233; color:#f39c12; border-radius:4px; border:1px solid #f39c12;">Widerstand</div>
                                <div class="has-tooltip" data-tooltip="Übermacht: Hat die gegnerische Karte einen HÖHEREN Basis-Score als der Separatist, ruft dieser sofort Verstärkung und erhält pauschal +2.5 Score dazu.&#10;&#10;  Limit: Formation (Mindestens 4 benötigt)" style="cursor:help; padding:3px 6px; background:#e67e2233; color:#e67e22; border-radius:4px; border:1px solid #e67e22;">Separatist</div>
                                <div class="has-tooltip" data-tooltip="Raserei: Durch unkontrollierte Wut schwankt der Score des Monsters absolut unberechenbar und zufällig zwischen -20% und +20%.&#10;&#10;  Limit: Formation (Mindestens 2 benötigt)" style="cursor:help; padding:3px 6px; background:#8b451333; color:#8b4513; border-radius:4px; border:1px solid #8b4513;">Monster</div>`;

file = file.replace(/<div style="display:flex; flex-wrap:wrap; gap:10px; margin-top:5px;">[\s\S]*?<div style="width:100%; color:#2ed573; margin-top:10px; font-weight:bold; border-bottom:1px solid #444;">Truppen-Formationen \(Mindestens benötigt\)<\/div>/, '<div style="display:flex; flex-wrap:wrap; gap:10px; margin-top:5px;">\n' + exclusiveHtml + '\n                                <div style="width:100%; color:#2ed573; margin-top:10px; font-weight:bold; border-bottom:1px solid #444;">Truppen-Formationen (Mindestens benötigt)</div>');

file = file.replace(/<div style="width:100%; color:#2ed573; margin-top:10px; font-weight:bold; border-bottom:1px solid #444;">Truppen-Formationen \(Mindestens benötigt\)<\/div>[\s\S]*?<\/div>\s*<hr style="border-color:#333; margin:0;">/, '<div style="width:100%; color:#2ed573; margin-top:10px; font-weight:bold; border-bottom:1px solid #444;">Truppen-Formationen (Mindestens benötigt)</div>\n' + formationHtml + '\n                            </div>\n\n                            <hr style="border-color:#333; margin:0;">');

fs.writeFileSync('d:/Programmieren/Ranker/index.html', file);
