export const TITLES = {
    starwars: [
        { id: 'sw_0', name: 'Kein Titel', required: 0 },
        { id: 'sw_1', name: 'Jüngling', required: 5 },
        { id: 'sw_2', name: 'Padawan', required: 20 },
        { id: 'sw_3', name: 'Jedi-Ritter', required: 50 },
        { id: 'sw_4', name: 'Jedi-Meister', required: 100 },
        { id: 'sw_5', name: 'Großmeister', required: 250 },
        { id: 'sw_6', name: 'Machtgeist', required: 500 },
        { id: 'sw_tut_master', name: 'Meister der Taktik', required: -1, condition: { type: 'custom', desc: 'Besiege alle Tutorial-Bots' } },
        { id: 'sw_secret_1', name: 'Der Auserwählte', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Darth Vader'] } },
        { id: 'sw_secret_2', name: 'Zwillingssonnen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Luke Skywalker', 'Leia Organa'] } },
        { id: 'sw_secret_3', name: 'Weeb', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Fino Bloodstone', 'Monkey D. Ruffy'] } },
        { id: 'sw_secret_4', name: 'Der Klonkrieg', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Obi-Wan Kenobi', 'Ahsoka Tano', 'Captain Rex', 'Commander Cody'] } },
        { id: 'sw_secret_5', name: 'Helden der Rebellion', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Luke Skywalker', 'Leia Organa', 'Han Solo', 'Chewbacca', 'C-3PO'] } },
        { id: 'sw_secret_6', name: 'Regel der Zwei', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Emperor Palpatine', 'Darth Vader'] } },
        { id: 'sw_secret_7', name: 'Clan der Zwei', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Din Djarin', 'Grogu'] } },
        { id: 'sw_secret_8', name: 'Dathomirs Erbe', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Asajj Ventress', 'Mother Talzin', 'Savage Opress', 'Darth Maul'] } },
        { id: 'sw_secret_9', name: 'Kopfgeldjäger Elite', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Boba Fett', 'Jango Fett', 'Bossk', 'Cad Bane', 'Aurra Sing'] } },
        { id: 'sw_secret_10', name: 'Meister & Schüler', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Ahsoka Tano'] } },
        { id: 'sw_secret_11', name: 'Brüder im Geiste', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Captain Rex', 'Commander Cody', 'Fives', 'Echo', 'Jesse'] } },
        { id: 'sw_secret_12', name: 'Das Syndikat', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Darth Maul', 'Qi\'ra', 'Dryden Vos'] } },
        { id: 'sw_secret_13', name: 'Die Dunkle Bedrohung', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Qui-Gon Jinn', 'Obi-Wan Kenobi', 'Darth Maul'] } },
        { id: 'sw_secret_14', name: 'Hallo Wie Gehts Denn So', required: -1, secret: true, condition: { type: 'has_characters', chars: ['General Grievous', 'Obi-Wan Kenobi'] } },
        { id: 'sw_secret_15', name: 'Verrat auf Coruscant', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Emperor Palpatine', 'Mace Windu', 'Kit Fisto', 'Saesee Tiin'] } },
        { id: 'sw_secret_16', name: 'Schmuggler Duo', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Han Solo', 'Chewbacca'] } },
        { id: 'sw_secret_17', name: 'Rebellenkommando', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jyn Erso', 'Cassian Andor', 'K-2SO'] } },
        { id: 'sw_secret_18', name: 'Die Letzten Jedi', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Luke Skywalker', 'Rey Skywalker', 'Kylo Ren'] } },
        { id: 'sw_secret_19', name: 'Familientreffen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Padme Amidala', 'Luke Skywalker', 'Leia Organa'] } },
        { id: 'sw_secret_20', name: 'Dunkles Erwachen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Supreme Leader Snoke', 'Kylo Ren', 'General Hux'] } },
        { id: 'sw_secret_21', name: 'Ghost Crew', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Hera Syndulla', 'Kanan Jarrus', 'Ezra Bridger', 'Sabine Wren', 'Chopper'] } },
        { id: 'sw_secret_22', name: 'Macht der Hexen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Mother Talzin', 'Merrin', 'Asajj Ventress'] } },
        { id: 'sw_secret_23', name: 'Erzfeinde', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Obi-Wan Kenobi', 'Darth Maul'] } },
        { id: 'sw_secret_24', name: 'Loyalität zur Republik', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Padme Amidala', 'Bail Organa', 'Mon Mothma'] } },
        { id: 'sw_secret_25', name: 'Glückspilz', required: -1, secret: true, condition: { type: 'special_top5' } },
        { id: 'sw_secret_26', name: 'Pechvogel', required: -1, secret: true, condition: { type: 'special_bottom5' } },
        { id: 'sw_secret_27', name: 'Seelenverwandte', required: -1, secret: true, condition: { type: 'special_versus_match' } },
        { id: 'sw_secret_28', name: 'Absolute Gegensätze', required: -1, secret: true, condition: { type: 'special_versus_opposite' } },
        { id: 'sw_secret_29', name: 'Perfektion', required: -1, secret: true, condition: { type: 'special_versus_perfect' } },
        { id: 'sw_secret_30', name: 'Mandalorianer', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Din Djarin', 'Bo-Katan Kryze', 'Pre Vizsla'] } },
        { id: 'sw_secret_31', name: 'Commander', required: -1, secret: true, condition: { type: 'has_tag_in_round', count: 5, tag: 'commander' } },
        { id: 'sw_secret_32', name: 'Rex & Cody', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Captain Rex', 'Commander Cody'] } },
        { id: 'sw_secret_33', name: 'Der Fremde', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Qimir (Der Fremde)', 'Osha Aniseya'] } },
        { id: 'sw_secret_34', name: 'Die Acolyte', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Mae Aniseya', 'Osha Aniseya'] } },
        { id: 'sw_secret_35', name: 'Machtfaden', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Qimir (Der Fremde)', 'Mae Aniseya'] } },
        { id: 'sw_secret_36', name: 'Tragödie von Brendok', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Osha Aniseya', 'Mae Aniseya', 'Qimir (Der Fremde)'] } },
        { id: 'sw_secret_37', name: 'Strebsamer Padawan', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jecki Lon', 'Osha Aniseya'] } },
        { id: 'sw_secret_38', name: 'Meesa Darth', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Darth Jar Jar', 'Jar Jar Binks'] } },
        { id: 'sw_secret_39', name: 'Gungan-Diplomatie', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jar Jar Binks', 'Padme Amidala'] } },
        { id: 'sw_secret_40', name: 'Die Mortis-Götter', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Der Vater', 'Der Sohn', 'Die Tochter'] } },
        { id: 'sw_secret_41', name: 'Verkörperung des Lichts', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Die Tochter', 'Ahsoka Tano'] } },
        { id: 'sw_secret_42', name: 'Schatten von Mortis', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Der Sohn', 'Anakin Skywalker'] } },
        { id: 'sw_secret_43', name: 'Das Gleichgewicht', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Der Vater', 'Anakin Skywalker'] } },
        { id: 'sw_secret_44', name: 'Bankenclan-Strippenzieher', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Rush Clovis', 'Padme Amidala'] } },
        { id: 'sw_secret_45', name: 'Schwestern der Unterwelt', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Trace Martez', 'Rafa Martez'] } },
        { id: 'sw_secret_46', name: 'Martez-Schmuggel', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Trace Martez', 'Rafa Martez', 'Ahsoka Tano'] } },
        { id: 'sw_secret_47', name: 'Schatten-Lord', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Darth Malgus', 'Darth Vader'] } },
        { id: 'sw_secret_48', name: 'Old Republic', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Darth Malgus', 'HK-47'] } },
        { id: 'sw_secret_49', name: 'Skeleton Crew', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jod Na Nawood', 'Neel'] } },
        { id: 'sw_secret_50', name: 'Spionage-Meister', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Suchdroide', 'Spybot'] } },
        { id: 'sw_secret_51', name: 'Rollende Zerstörung', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Droideka', 'Zwergspinnendroide'] } },
        { id: 'sw_secret_52', name: 'Separatistische Übermacht', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Droideka', 'General Grievous', 'Zwergspinnendroide'] } },
        { id: 'sw_secret_53', name: 'Dunkles Bündnis', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Qimir (Der Fremde)', 'Darth Malgus', 'Darth Jar Jar'] } },
        { id: 'sw_secret_54', name: 'Licht & Schatten', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Der Sohn', 'Die Tochter'] } },
        { id: 'sw_secret_55', name: 'Zwei als Eins', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Osha Aniseya', 'Jecki Lon'] } },
        { id: 'sw_secret_56', name: 'Entwickler-Segen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jonas', 'Fino Bloodstone', 'Monkey D. Ruffy'] } },
        { id: 'sw_secret_57', name: 'Das wahre Meme', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jonas', 'Fino Bloodstone', 'Monkey D. Ruffy'] } },
        { id: 'sw_secret_58', name: 'Müllmühle', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Han Solo', 'Millennium Falcon'] } },
        { id: 'sw_secret_59', name: 'Trench Run', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Luke Skywalker', 'X-Wing Starfighter', 'Darth Vader'] } },
        { id: 'sw_secret_60', name: 'Todesstern-Architekten', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Death Star', 'Director Krennic', 'Grand Moff Tarkin'] } },
        { id: 'sw_secret_61', name: 'Fliegende Schrottkiste', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Razor Crest', 'Din Djarin'] } },
        { id: 'sw_secret_62', name: 'Kampf der Titanen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Yoda', 'Emperor Palpatine'] } },
        { id: 'sw_secret_63', name: 'Schicksal auf Mustafar', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Obi-Wan Kenobi', 'Padme Amidala'] } },
        { id: 'sw_secret_64', name: 'Ich bin dein Vater', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Darth Vader', 'Luke Skywalker'] } },
        { id: 'sw_secret_65', name: 'Meister und gefallener Schüler', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Darth Vader', 'Ahsoka Tano'] } },
        { id: 'sw_secret_66', name: 'Das Hutten-Kartell', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jabba the Hutt', 'Ziro the Hutt', 'Gardulla the Hutt'] } },
        { id: 'sw_secret_67', name: 'Weg des Mandalore', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Din Djarin', 'Bo-Katan Kryze', 'The Armorer'] } },
        { id: 'sw_secret_68', name: 'Vater & Klon', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jango Fett', 'Boba Fett'] } },
        { id: 'sw_secret_69', name: 'Grube von Carkoon', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Sarlacc', 'Boba Fett'] } },
        { id: 'sw_secret_70', name: 'Meister der Bestien', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Rancor', 'Wampa', 'Nexu'] } },
        { id: 'sw_secret_71', name: 'Die wahren Helden', required: -1, secret: true, condition: { type: 'has_characters', chars: ['R2-D2', 'C-3PO'] } },
        { id: 'sw_secret_72', name: 'Goldenes Duo', required: -1, secret: true, condition: { type: 'has_characters', chars: ['C-3PO', 'Padme Amidala'] } },
        { id: 'sw_secret_73', name: 'Schrottsammler', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Rey Skywalker', 'BB-8'] } },
        { id: 'sw_secret_74', name: 'Inquisition', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Grand Inquisitor', 'Second Sister', 'Third Sister'] } },
        { id: 'sw_secret_75', name: 'Meister und Söldner', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Baylan Skoll', 'Shin Hati'] } },
        { id: 'sw_secret_76', name: 'Die Letzte Ordnung', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Emperor Palpatine', 'Kylo Ren'] } },
        { id: 'sw_secret_77', name: 'Gute alte Zeiten', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Lando Calrissian', 'Han Solo', 'Chewbacca'] } },
        { id: 'sw_secret_78', name: 'Die oberste Direktive', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Commander Fox', 'Emperor Palpatine'] } },
        { id: 'sw_secret_79', name: 'Der Rat der Jedi', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Mace Windu', 'Yoda', 'Ki-Adi-Mundi', 'Plo Koon'] } },
        { id: 'sw_secret_80', name: 'Einheit 99', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Hunter', 'Wrecker', 'Tech', 'Crosshair'] } },
        { id: 'sw_new_1', name: 'Der Sammler', required: -1, condition: { type: 'stats_check', desc: 'Kaufe 50 Booster-Packs' } },
        { id: 'sw_new_2', name: 'Stammkunde', required: -1, condition: { type: 'stats_check', desc: 'Kaufe 5 Karten auf dem Schwarzmarkt' } },
        { id: 'sw_new_3', name: 'Kartell-Boss', required: -1, condition: { type: 'stats_check', desc: 'Sammle 10.000 Credits an' } },
        { id: 'sw_new_4', name: 'Jedi-Meister (Cardgame)', required: -1, condition: { type: 'stats_check', desc: 'Erreiche 100 Siege im Cardgame' } },
        { id: 'sw_new_5', name: 'Sith-Lord', required: -1, condition: { type: 'stats_check', desc: 'Besiege 50 Gegner im Abenteuer-Modus' } },
        { id: 'sw_new_6', name: 'Glückspilz (Packs)', required: -1, condition: { type: 'stats_check', desc: 'Ziehe eine legendäre Karte aus einem Standard-Pack' } },
        { id: 'sw_new_7', name: 'Starwarsdle-Adept', required: -1, condition: { type: 'stats_check', desc: 'Errate den Charakter im Starwarsdle im ersten Versuch' } },
        { id: 'sw_new_8', name: 'Galaxis-Kenner', required: -1, condition: { type: 'stats_check', desc: 'Gewinne insgesamt 50 Starwarsdle-Spiele' } },
        { id: 'sw_new_9', name: 'Klon-Kommandant', required: -1, condition: { type: 'stats_check', desc: 'Besitze alle Karten mit dem "Klon"-Tag' } },
        { id: 'sw_new_10', name: 'Kopfgeldjäger', required: -1, condition: { type: 'stats_check', desc: 'Gewinne ein Match mit aktivem Kopfgeld-Buff' } },
        { id: 'sw_new_11', name: 'Abenteurer', required: -1, condition: { type: 'stats_check', desc: 'Erreiche Level 20 im Abenteuer-Modus' } },
        { id: 'sw_new_12', name: 'Galaktischer Eroberer', required: -1, condition: { type: 'stats_check', desc: 'Belege Platz 1 in der Wöchentlichen Galaktischen Liga' } },
        { id: 'sw_new_13', name: 'Senatsmitglied', required: 500, condition: { type: 'stats_check', desc: 'Ranke 500 Charaktere im normalen Ranking-Modus' } },
        { id: 'sw_new_14', name: 'Galaktischer Architekt', required: -1, condition: { type: 'stats_check', desc: 'Baue ein Deck aus 5 verschiedenen Fraktionen' } },
        { id: 'sw_new_15', name: 'Droiden-Techniker', required: -1, condition: { type: 'stats_check', desc: 'Spiele eine Runde Cardgame mit einem Deck nur aus Droiden' } },
        { id: 'sw_new_16', name: 'Schwarzmarkt-Stammgast', required: -1, condition: { type: 'stats_check', desc: 'Kaufe 10-mal auf dem Schwarzmarkt ein' } },
        { id: 'sw_new_17', name: 'Großinquisitor', required: -1, condition: { type: 'stats_check', desc: 'Besiege 10 Jedi-Decks im Bot-Match' } },
        { id: 'sw_new_18', name: 'Mandalorianer (Boss)', required: -1, condition: { type: 'stats_check', desc: 'Besiege den Level 5 Boss im Abenteuer-Modus' } },
        { id: 'sw_new_19', name: 'Nachtschwester', required: -1, condition: { type: 'stats_check', desc: 'Gewinne ein Cardgame-Match mit einer wiederbelebten Karte' } },
        { id: 'sw_new_20', name: 'Taktiker', required: -1, condition: { type: 'stats_check', desc: 'Gewinne ein Cardgame-Match mit exakt 1 Punkt Vorsprung' } },
        { id: 'sw_new_21', name: 'Vom Pech verfolgt', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Verliere 5 Cardgame-Matches in Folge' } },
        { id: 'sw_new_22', name: 'Bankrott', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Gib all deine Credits aus, sodass du exakt 0 hast' } },
        { id: 'sw_new_23', name: 'Verräter', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Spiele ein Deck aus exakt 4 Sith und 3 Jedi' } },
        { id: 'sw_new_24', name: 'Unantastbar', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Gewinne ein Cardgame-Match ohne Rundenverlust' } },
        { id: 'sw_new_25', name: 'Allwissend', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Löse Starwarsdle in unter 10 Sekunden' } },
        { id: 'sw_new_26', name: 'Letzte Hoffnung', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Gewinne LV20 Boss mit letzter Karte nach Unentschieden' } },
        { id: 'sw_new_27', name: 'Schrottsammler (Booster)', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Ziehe nur graue Karten in einem Booster-Pack' } },
        { id: 'sw_new_28', name: 'Pazifist', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Beende ein Match unentschieden' } },
        { id: 'sw_new_29', name: 'Rebellions-Funke', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Besiege als Rebellen-Deck ein Imperium-Deck' } },
        { id: 'sw_new_30', name: 'Entwickler-Liebling', required: -1, secret: true, condition: { type: 'stats_check', desc: 'Klicke 10 Mal schnell auf die Patchnotes-Box' } }
    ],
    waifu: [
        { id: 'wf_0', name: 'Kein Titel', required: 0 },
        { id: 'wf_1', name: 'Kouhai', required: 5 },
        { id: 'wf_2', name: 'Senpai', required: 20 },
        { id: 'wf_3', name: 'Sensei', required: 50 },
        { id: 'wf_4', name: 'Weeb', required: 100 },
        { id: 'wf_5', name: 'Otaku', required: 250 },
        { id: 'wf_6', name: 'Isekai-Gott', required: 500 },
        { id: 'wf_secret_1', name: 'Tsundere-Meister', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Asuka Langley Soryu', 'Taiga Aisaka'] } },
        { id: 'wf_secret_2', name: 'Glückspilz', required: -1, secret: true, condition: { type: 'special_top5' } },
        { id: 'wf_secret_3', name: 'Pechvogel', required: -1, secret: true, condition: { type: 'special_bottom5' } },
        { id: 'wf_secret_4', name: 'Seelenverwandte', required: -1, secret: true, condition: { type: 'special_versus_match' } },
        { id: 'wf_secret_5', name: 'Perfektion', required: -1, secret: true, condition: { type: 'special_versus_perfect' } },
        { id: 'wf_secret_6', name: 'Absolute Gegensätze', required: -1, secret: true, condition: { type: 'special_versus_opposite' } }
    ]
};
