export const TITLES = {
    starwars: [
        { id: 'sw_0', name: 'Kein Titel', required: 0 },
        { id: 'sw_1', name: 'Jüngling', required: 5 },
        { id: 'sw_2', name: 'Padawan', required: 20 },
        { id: 'sw_3', name: 'Jedi-Ritter', required: 50 },
        { id: 'sw_4', name: 'Jedi-Meister', required: 100 },
        { id: 'sw_5', name: 'Großmeister', required: 250 },
        { id: 'sw_6', name: 'Machtgeist', required: 500 },
        { id: 'sw_secret_1', name: 'Der Auserwählte', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Darth Vader'] } },
        { id: 'sw_secret_2', name: 'Zwillingssonnen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Luke Skywalker', 'Leia Organa'] } },
        { id: 'sw_secret_3', name: 'Weeb', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Fino Bloodstone', 'Monkey D. Ruffy'] } },
        { id: 'sw_secret_4', name: 'Der Klonkrieg', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Obi-Wan Kenobi', 'Ahsoka Tano', 'Captain Rex', 'Commander Cody'] } },
        { id: 'sw_secret_5', name: 'Helden der Rebellion', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Luke Skywalker', 'Leia Organa', 'Han Solo', 'Chewbacca', 'C-3PO'] } },
        { id: 'sw_secret_6', name: 'Regel der Zwei', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Emperor Palpatine', 'Darth Vader'] } },
        { id: 'sw_secret_7', name: 'Clan der Zwei', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Din Djarin', 'Grogu'] } },
        { id: 'sw_secret_8', name: 'Dathomirs Erbe', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Asajj Ventress', 'Mother Talzin', 'Savage Opress', 'Darth Maul'] } },
        { id: 'sw_secret_9', name: 'Kopfgeldjäger Elite', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Boba Fett', 'Jango Fett', 'Bossk', 'Cad Bane', 'Aurra Sing'] } },
        { id: 'sw_secret_10', name: 'Meister & Schüler', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Ahsoka Tano'] } },
        { id: 'sw_secret_11', name: 'Brüder im Geiste', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Captain Rex', 'Commander Cody', 'Fives', 'Echo', 'Jesse'] } },
        { id: 'sw_secret_12', name: 'Das Syndikat', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Darth Maul', 'Qi\'ra', 'Dryden Vos'] } },
        { id: 'sw_secret_13', name: 'Die Dunkle Bedrohung', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Qui-Gon Jinn', 'Obi-Wan Kenobi', 'Darth Maul'] } },
        { id: 'sw_secret_14', name: 'Hallo Wie Gehts Denn So', required: -1, secret: true, condition: { type: 'has_characters', chars: ['General Grievous', 'Obi-Wan Kenobi'] } },
        { id: 'sw_secret_15', name: 'Verrat auf Coruscant', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Emperor Palpatine', 'Mace Windu', 'Kit Fisto', 'Saesee Tiin'] } },
        { id: 'sw_secret_16', name: 'Schmuggler Duo', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Han Solo', 'Chewbacca'] } },
        { id: 'sw_secret_17', name: 'Rebellenkommando', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Jyn Erso', 'Cassian Andor', 'K-2SO'] } },
        { id: 'sw_secret_18', name: 'Die Letzten Jedi', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Luke Skywalker', 'Rey Skywalker', 'Kylo Ren'] } },
        { id: 'sw_secret_19', name: 'Familientreffen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Anakin Skywalker', 'Padme Amidala', 'Luke Skywalker', 'Leia Organa'] } },
        { id: 'sw_secret_20', name: 'Dunkles Erwachen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Supreme Leader Snoke', 'Kylo Ren', 'General Hux'] } },
        { id: 'sw_secret_21', name: 'Ghost Crew', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Hera Syndulla', 'Kanan Jarrus', 'Ezra Bridger', 'Sabine Wren', 'Chopper'] } },
        { id: 'sw_secret_22', name: 'Macht der Hexen', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Mother Talzin', 'Merrin', 'Asajj Ventress'] } },
        { id: 'sw_secret_23', name: 'Erzfeinde', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Obi-Wan Kenobi', 'Darth Maul'] } },
        { id: 'sw_secret_24', name: 'Loyalität zur Republik', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Padme Amidala', 'Bail Organa', 'Mon Mothma'] } },
        { id: 'sw_secret_25', name: 'Glückspilz', required: -1, secret: true, condition: { type: 'special_top5' } },
        { id: 'sw_secret_26', name: 'Pechvogel', required: -1, secret: true, condition: { type: 'special_bottom5' } },
        { id: 'sw_secret_27', name: 'Seelenverwandte', required: -1, secret: true, condition: { type: 'special_versus_match' } },
        { id: 'sw_secret_28', name: 'Absolute Gegensätze', required: -1, secret: true, condition: { type: 'special_versus_opposite' } },
        { id: 'sw_secret_29', name: 'Perfektion', required: -1, secret: true, condition: { type: 'special_versus_perfect' } },
        { id: 'sw_secret_30', name: 'Mandalorianer', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Din Djarin', 'Bo-Katan Kryze', 'Pre Vizsla'] } },
        { id: 'sw_secret_31', name: 'Commander', required: -1, secret: true, condition: { type: 'has_tag_in_round', count: 5, tag: 'commander' } },
        { id: 'sw_secret_32', name: 'Rex & Cody', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Captain Rex', 'Commander Cody'] } }
    ],
    waifu: [
        { id: 'wf_0', name: 'Kein Titel', required: 0 },
        { id: 'wf_1', name: 'Kouhai', required: 5 },
        { id: 'wf_2', name: 'Senpai', required: 20 },
        { id: 'wf_3', name: 'Sensei', required: 50 },
        { id: 'wf_4', name: 'Weeb', required: 100 },
        { id: 'wf_5', name: 'Otaku', required: 250 },
        { id: 'wf_6', name: 'Isekai-Gott', required: 500 },
        { id: 'wf_secret_1', name: 'Tsundere-Meister', required: -1, secret: true, condition: { type: 'has_characters', chars: ['Asuka Langley Soryu', 'Taiga Aisaka'] } },
        { id: 'wf_secret_2', name: 'Glückspilz', required: -1, secret: true, condition: { type: 'special_top5' } },
        { id: 'wf_secret_3', name: 'Pechvogel', required: -1, secret: true, condition: { type: 'special_bottom5' } },
        { id: 'wf_secret_4', name: 'Seelenverwandte', required: -1, secret: true, condition: { type: 'special_versus_match' } },
        { id: 'wf_secret_5', name: 'Perfektion', required: -1, secret: true, condition: { type: 'special_versus_perfect' } },
        { id: 'wf_secret_6', name: 'Absolute Gegensätze', required: -1, secret: true, condition: { type: 'special_versus_opposite' } }
    ]
};
